# 默认配置，所有 profile 都会继承这些设置
[profile.default]
src = "src"
out = "../../out"
libs = ["lib"]
cache_path = "../../cache"  
broadcast = "../../broadcast"  
solc = "0.8.20" 

# 依赖映射
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# 本地开发环境
[profile.local]

# Sepolia 测试网环境
[profile.sepolia]

# 主网环境
[profile.mainnet]

# RPC 配置
[rpc_endpoints]
local = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC}"
mainnet = "${MAINNET_RPC}"

# Etherscan 配置
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }