[profile.default]
src = "src"
test = "test"              # 添加这一行
out = "../../out"           # 输出到根目录
libs = ["lib"]
cache_path = "../../cache"  # 缓存到根目录
broadcast = "../../broadcast"  # 广播到根目录

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# 指定本工程项目使用的 compiler 版本
solc = "0.8.20" 

# 添加依赖映射
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]